### ISSUE TITLE
Functions in the HANDMADE_MATH_IMPLEMENTATION section are missing the HMM_PREFIX(...) macro

### ISSUE THREAD

**Issue by GsxCasper** [HandmadeMath/Handmade-Math#119]
As mentioned in the title, all the functions defined within `HANDMADE_MATH_IMPLEMENTATION` do hardcode the `HMM_` prefix (for example `HMM_Rotate` instead of `HMM_PREFIX(Rotate)`).
This causes linking to fail to those who define `HMM_PREFIX` and use those functions.

(btw I tried to open a pr with the fix but I don't have permission to push. I'm not sure if I need to be whitelisted to this repo in order to push?)

**Comment by bvisness** [comment]
Sorry about that. If you want to fix it up yourself, just make a fork of the repository, push your change there, and then make a pull request. (See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

Otherwise I can fix this up this evening.

**Comment by GsxCasper** [comment]
Thanks, I thought it was a simple enough change that I could just fix it but I wrongly assumed I'd just create a branch and make a PR from there.

Thanks for showing me how to do it through forking! Opened https://github.com/HandmadeMath/Handmade-Math/pull/120
