### ISSUE TITLE
Clarify ambiguous term "Column-major"

### ISSUE THREAD

**Issue by makuto** [HandmadeMath/Handmade-Math#124]
Re issue #89: I'm confused. Isn't this true? Or is there something I'm not understanding about row vs. column major?
For example:

```C++
#include <stdio.h>
#include "HandmadeMath.h"

typedef hmm_mat4 mat4;
mat4 mat4Identity()
{
	return HMM_Mat4d(1.f);
}

void mat4Print(mat4 mat)
{
	int row = 0;
	while (row < 4)
	{
		printf("%d [%f %f %f %f]\n", row, mat[row][0], mat[row][1], mat[row][2], mat[row][3]);
		++row;
	}
}

int main()
{
	mat4 matA = mat4Identity();
	mat4Print(HMM_MultiplyMat4(matA, HMM_Translate({1.f, 2.f, 3.f})));
	mat4Print(HMM_Rotate(45.f, gUpAxis));
	return 0;
}
```

outputs:

```C
0 [1.000000 0.000000 0.000000 0.000000]
1 [0.000000 1.000000 0.000000 0.000000]
2 [0.000000 0.000000 1.000000 0.000000]
3 [1.000000 2.000000 3.000000 1.000000]

0 [0.707107 0.000000 -0.707107 0.000000]
1 [0.000000 1.000000 0.000000 0.000000]
2 [0.707107 0.000000 0.707107 0.000000]
3 [0.000000 0.000000 0.000000 1.000000]
```

Which is what I expect: the translation `(1.f, 2.f, 3.f)` is properly stored in the 4th row of the matrix, where columns 1, 2, and 3 are contiguous in memory.

I did some more reading, and found this thorough discussion: [Column Vectors vs. Row Vectors](http://steve.hollasch.net/cgindex/math/matrix/column-vec.html). I don't fully understand what they were getting at, but I think the terminology really should be clarified in Handmade Math.

Whether it's row-major or column-major depends on how you write it. My `mat4Print` prints it row-major, as if you were printing a pixel array (and not destroying your cache).

To clarify, the matrices are *stored* in row-major order, but you can choose to *think* of them in column-major order, right? I'm used to matrices being both stored and thought-of in row-major order, as if rendering the matrix out as a image stored from the top left corner, row by row.

However, it is row *vector*, which is what I expected, and what confused me when seeing "column-major". I think the terminology should be updated to say row-vector instead of column-major, because the latter is an ambiguous term.

**Comment by bvisness** [comment]
After writing a response, then reading the post you linked in more detail, then reading your code, then re-reading your question, I am confident that Handmade Math is column-vector and column-major, and I will try to explain why. Apologies if you already know some of the material presented here; I'm trying to explain the issue as holistically as I can.

## Graphics APIs don't actually care about rows or columns

Linear transformations can be represented by a matrix, where the columns of the matrix are the basis vectors of the space after the transformation. That's a mouthful, so here's an example.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/4707402/107319919-5679dc00-6a65-11eb-8fef-37027c66b246.png">

Notice that the individual vectors are represented as columns, the columns of the matrix are formed from the transformed basis vectors, and the matrix is multiplied on the left of the blue vector to transform it.

This turns out to be a matter of convention, as we can instead represent everything as rows, and multiply the matrix on the right, and get the same result:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/4707402/107320590-9bead900-6a66-11eb-9d5f-28d68c9edb99.png">

Importantly, though, both of these are really performing _exactly_ the same computation. The computer doesn't know if you like to write your vectors vertically or horizontally; you are just computing two numbers, and computing them the exact same way. Whether you build your matrix from column vectors and multiply on the left, or build your matrix from row vectors and multiply on the right, is essentially just a notation detail.

This is what the post you linked was talking about; OpenGL simply expects 16 numbers, where 1-4 correspond to your first basis vector, 5-8 correspond to your second, and so on:

>  The data elements 0 through 15 are in the same order for a "row major" matrix as for a "column major" matrix. To beat it to death: the OpenGL matrix stores translation values in elements 12,13,14.

## Handmade Math _does_ care about rows and columns

It does, really, and you can tell because Handmade Math has you multiply on the left. In fact, Handmade Math currently lacks any ability to do `vector * matrix` instead of `matrix * vector`, which is perhaps a bit limiting but serves this argument well.

The fact of the matter is that regardless of representation in memory, the code you write reflects the math notation you prefer to use. If you consider vectors to be written vertically ("column-vector"), then matrices are multiplied on the left. If you consider vectors to be written horizontally ("row-vector"), then matrices are multiplied on the right. Fabian Giesen explains it better and in more detail on [his blog](https://fgiesen.wordpress.com/2012/02/12/row-major-vs-column-major-row-vectors-vs-column-vectors/), but ultimately you've got to match up the dimensions in order to do matrix multiplication.

Handmade Math is designed to correspond with the mathematical convention you see in OpenGL documentation (and apparently everywhere but DirectX), where vectors are written vertically, and transformation matrices are therefore built from columns. So we would call Handmade Math "column-vector".

## Storage is another thing altogether

So is Handmade Math column-major as well as column-vector? Yes, absolutely:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/4707402/107329706-26870480-6a76-11eb-839f-5c62e4760cab.png">

This is what the `HMM_Translate` matrix looks like since Handmade Math is column-vector, and the elements of each column are stored contiguously, so Handmade Math is column-vector and its matrices are column-major.

## Some final specific things

In your examples you index your matrix like `mat[row][0]`. This is wrong, and hopefully now you can see why; if you want to print a Handmade Math matrix in correct mathematical notation, it should be `mat[0][row]`. Flipping that around, your code outputs:

```
0 [1.000000 0.000000 0.000000 1.000000]
1 [0.000000 1.000000 0.000000 2.000000]
2 [0.000000 0.000000 1.000000 3.000000]
3 [0.000000 0.000000 0.000000 1.000000]

0 [0.707107 0.000000 0.707107 0.000000]
1 [0.000000 1.000000 0.000000 0.000000]
2 [-0.707107 0.000000 0.707107 0.000000]
3 [0.000000 0.000000 0.000000 1.000000]
```

Now, as you can see, the translation values are in the fourth column instead of the fourth row.

## Terminology 🙃 

So yeah, in summary, Handmade Math is definitely column-vector and column-major. The terminology is confusing, but it is not ambiguous. I hope this clears things up for you; if not, hopefully I can address any other concerns you have.

Thanks for the fun diversion tonight 😁

**Comment by makuto** [comment]
I had to have the realization that the only thing that really determines what you call it is actually how you interpret the vector, and that determines what you need to call the matrix. Esp. Fabian's STv example drilled it home.
