### ISSUE TITLE
Doesn't build in C (non-C++) mode

### ISSUE THREAD

**Issue by DanielGibson** [HandmadeMath/Handmade-Math#57]
It currently doesn't build in C mode, because `NLerp` uses `HMM_Normalize()` instead of `HMM_NormalizeQuaternion()`.

I also doubt that a compiler enforcing real C99 mode would be very happy about your usage of inline in the implementation.  
Having function declarations like `extern float HMM_CosF(float Angle);` and then the implementation as `inline float HMM_CosF(float Angle)` looks very wrong.  
And C99 and newer has that weird thing where functions declared inline in the header must be implemented twice: inline in the header *and* not-inline in the implementation - which is pretty much the opposite of what you're doing there (to get classic/C++ inline behavior one would just supply a `static inline` implementation in the header).

**Comment by bvisness** [comment]
Ack. This is what we get for only running our tests in C++ mode. I'll dig into these issues and see what I can do.

**Comment by DanielGibson** [comment]
Great, thank you!

Regarding the C99 thing, it may make sense to test with -std=c99 and 
using two 2 .c files, so only one of them has #define 
HANDMADE_MATH_IMPLEMENTATION and the other can't "see" the function 
implementations

**Comment by bvisness** [comment]
@DanielGibson We definitely need to do something else for inlining because, as I'm just now realizing, the implementation has to be visible to everyone...

If we do `static inline` for all of our functions, then we don't need separate function definitions, right?

Also, if we go the `static inline` route, and the compiler decides not to inline a particular function, we end up with a separate definition of that function in every translation unit that uses it, right? Do you think that's a problem for a math library whose functions may be used all over the place?

(If [this Stack Overflow answer](https://stackoverflow.com/questions/10291581/how-to-properly-inline-for-static-libraries) is correct, we could also do that crazy extern-declaration-in-source-file approach, but the author says it might not work well in MSVC.)

**Comment by DanielGibson** [comment]
Yeah, the definition of inline functions must be visible to everyone, and yes, static inline might lead to duplicate definitions in every source file using them (or with stupid compilers maybe even in source files that only #include the header and don't use the particular function?).

extern-declaration-in-source-file sounds wonky indeed, especially as MSVC doesn't properly support C99, and I'm also not sure if that works with C++ and if so, what standard of C++ is needed (C++03? C++11?).

What was wrong with the old approach where you just used `HMMDEF` everywhere?
Both `extern int foo(void);` in header and `extern int foo(void) { bar(); }` in the implementation should be totally valid (that's what stb_image.h does, for example).  
Alternatively you could also #define HMMDEF to nothing by default, because `int foo(void);` in a header is `extern` implicitly.  
If someone really wants everything to be inline, they can then do `#define HMMDEF static inline` and `#define HANDMADE_MATH_IMPLEMENTATION` before **every** #include of HandmadeMath.h

Mostly independent of this you *could* make some functions inline and define them in the header-part, this makes sense for extremely short functions - especially the C++ wrappers, but also lots of the other ones that are only one or two lines of "real" code - looking at the functions that would be most of them.

**Comment by bvisness** [comment]
The `static inline` approach makes the most sense to me, and I would be surprised if most compilers would choose *not* to inline a relatively short function that we specifically told it to inline. 

The old approach would work, yeah, but then we probably wouldn't get any inlining, anywhere, since the function implementations wouldn't be visible to other translation units. (Not that we are now, but the reason `HINLINE` exists in the first place is because it wasn't consistently generating object code to link against.) stb just doesn't even try to inline things.

I think the way C++ is compiled and linked is just fundamentally opposed to the idea of a library that gets inlined everywhere. It seems to be a choice between `static inline`, with the downsides of redundant function definitions in different translation units, and plain old `extern`, with no potential to inline.

Hopefully we can just let the user choose which they want.

**Comment by DanielGibson** [comment]
> It seems to be a choice between static inline, with the downsides of redundant function definitions in different translation units, and plain old extern, with no potential to inline.

Or, as I suggested, use both: static inline for short functions, old extern for longer ones like HMM_Rotate(), HMM_LookAt(), HMM_InverseQuaternion() etc, /maybe/ HMM_Power()

Btw, I wonder why there's always that pattern of `Type result = {0}; result = HMM_Fun(); return result;`
Why not directly `Type result = HMM_Fun(); return result;`? Especially in unoptimized debugbuilds and if type is a struct (and not just float) that might actually make a difference.
Related: things like 
```c
hmm_vec3 HMM_Vec3(float X, float Y, float Z)
{
    hmm_vec3 Result = {0};

    Result.X = X;
    Result.Y = Y;
    Result.Z = Z;

    return (Result);
}
```
Could be shorter (but IMO still very readable) with just
```c
HINLINE hmm_vec3
HMM_Vec3(float X, float Y, float Z)
{
    hmm_vec3 Result = {{ X, Y, Z }};
    return (Result);
}
```

**Comment by bvisness** [comment]
I'm not sure exactly why the weird pattern of explicitly initialize, then overwrite. I've kept up the pattern, assuming @StrangeZak had his reasons. (I seem to recall stuff about MSVC being terrible.) Feel free to make another issue for that 😄 

I'll work on resolving the inline stuff once #58 is taken care of.

**Comment by StrangeZak** [comment]
@DanielGibson For debugging the 1st option is much better to walk through and see what happens. Also, i just like the readability of the 1st option much more :) Sorry for not being active in this thread been out of town for a few days

**Comment by StrangeZak** [comment]
why was this issue reopened @bvisness

**Comment by bvisness** [comment]
Because the inline stuff hasn't been fixed yet.

**Comment by StrangeZak** [comment]
@bvisness I think now would probably be a good time to tackle this.
