### ISSUE TITLE
Making unit tests embeddable

### ISSUE THREAD

**Issue by revivalizer** [HandmadeMath/Handmade-Math#71]
Hello all,

I am using handmade math in a project, using a unity build. I'd like to keep this structure.

My project also has a mechanism for running unit tests. I'd like to fold the HMM unit tests in so they run seamlessly in my build.

This could be accomplished by splitting test/hmm_test.c into a test/hmm_test_runner.c and test/hmm_tests.h.

test_runner.c would contain the infrastructure necessary to run tests in a separate executable, and hmm_tests.h would contain the test "definitions". I would then use the test/hmm_tests.h file in my project, and provide my own macro set to map to my unit test structure.

I might also prefix the unit test related macros with HMMT to make it clear what's going on.

Before I jump in and implement this -- any objections? Alternate ideas?

**Comment by StrangeZak** [comment]
@bvisness The unit test system is all yours. Take this 😋

**Comment by bvisness** [comment]
I'm frankly not sure why you need to run our unit tests in your build, since we guarantee that all of our tests pass when we release a new version. I also don't think it makes sense to heavily modify our unit test setup to work with other people's projects, since Handmade Math is explicitly designed to be included as a single header file, not to have its entire git repo dumped into a project.

Feel free to make whatever modifications you want, but I don't expect that we will be changing the structure of the tests in this repo.

**Comment by revivalizer** [comment]
I grant that this is perhaps not a typical request, but I think we (as a community) should do more of this, because:

> we guarantee that all of our tests pass when we release a new version
But do you test on my particular combination of
- OS
- bitness
- compiler
- compiler options
- define set
- libc replacement
?

> Handmade Math is explicitly designed to be included as a single header file
While single headers are nice for distribution and compiling, in practice I think a lot of people are not setup that way. You loose the ability to easily feed back github pull requests for example, whereas having a subrepo or whatever retains that ability.

**Comment by bvisness** [comment]
Yeah, that's fair. I say go for it - as I thought about it more, I realized how little it actually changes the structure of the tests, but how much easier it makes things for you and others.

If you decide to prefix the test macros, I would prefer you prefix them with `HMT` (for HandmadeTest) instead of `HMMT`.
