### ISSUE TITLE
Rotate vector by quaternion?

### ISSUE THREAD

**Issue by Nairou** [HandmadeMath/Handmade-Math#86]
I don't know if I'm not seeing it or if it isn't available. Right now I can accomplish it by converting the quaternion to a mat4 and multiplying the vector by that. But I'd like to skip the mat4 step if possible, since it defeats the purpose of the quaternion.

**Comment by bvisness** [comment]
You're doing it right already. Quaternions and matrices are two different ways of encoding rotations, but quaternions can't interact with vectors directly because they are simply talking about different things.

Matrices and vectors speak the same language. A matrix describes a transformation by encoding what that transformation does to your basis vectors. For example, a 2x2 matrix that rotates counterclockwise by 90 degrees looks like this because it moves (1, 0) to (0, 1) and (0, 1) to (-1, 0):

```
   Where the y axis lands -┐
Where the x axis lands -┐  |
                        v  v

                        0 -1
                        1  0
```

(Watch this video for more info and fancy animations: https://youtu.be/kYB8IZa5AuE)

Quaternions, on the other hand, are a totally separate means of encoding rotation that uses complex numbers and is based on an [axis-angle representation](https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation) of rotation. Interactions between quaternions and vectors are simply undefined. But, because matrices and quaternions can both describe a rotation, we can convert between them, and use the matrix representation to rotate the vector.

Anyway, math aside, I understand that it might be helpful to have a function that rotates a vector by a given quaternion. If that is a common use case for you, I encourage you to write your own helper function to do so! Because it doesn't make sense from a math perspective, though, I don't think we'll be adding such a function to Handmade Math itself.

**Comment by bvisness** [comment]
Oh, and just to address one other point - it doesn't really "defeat the purpose of a quaternion". In a complex application, you may need to apply many rotations in sequence (such as a child object inheriting its parent's rotation) or interpolate between other rotations (such as in a character animation system). Quaternions are very good at this, and don't suffer from gimbal lock. You only need to convert to a mat4 at the very end, when you've calculated your final rotation and are ready to move some vectors into place.
