### ISSUE TITLE
No way to run tests on Windows

### ISSUE THREAD

**Issue by kavika13** [HandmadeMath/Handmade-Math#92]
Wondering if there's any interest in making project files (or some other build solution?) for running the test suite in MSVC.

I am happy to put them together if they'd be useful. I have VS 2015 and got those projects working there. Not sure if VS 2017 requires a separate solution version, but I could also make that project if it does.

I cannot get VS 2012 working without modifying the tests. C99 designated initializers weren't supported until VS 2013, it seems, and the tests use those. I could convert the tests to not use that feature (if the lib itself doesn't use it). I wanted to gauge interest in all this before starting that.

**Comment by StrangeZak** [comment]
Hmm... I think solution files are unique per Visual Studio version (I think they even change with minor patches) and the version of build toolchain the user has on. This might be a case for cMake, just so people can generate "solution" files for any platform

**Comment by bvisness** [comment]
I needed to use C99 designated initializers in order to make the tests run in both C and C++, so I doubt we'd be able to get rid of those. Although if you manage to find a way to make C register tests before the main function runs, by all means do so, because I struggled for quite a while to make that work.

Making the tests runnable within MSVC would be really good, though, considering how many of our users probably use MSVC. Our current test setup is built around Travis CI and gcc on my Macbook. CMake seems like a good option to investigate.

**Comment by bvisness** [comment]
Renamed to reflect the main gist of the problem. I think it would be reasonable to support just the C++ tests on Windows, and it would be fine to do it through a batch file to keep the problem reasonably scoped. This will never run in CI anyway, unless Travis adds MSVC support, so we can just do what it takes to sanity-check work locally before committing it.

**Comment by StrangeZak** [comment]
@bvisness So apparently you can run our tests on Windows now with TravisCI
